# version: "2"

services:
  image-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tfg
    hostname: manu
    volumes:
      - ./app:/root/app
      - ./data:/root/data
      - ./resources:/root/resources
    env_file:
      - .env
